/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EgControl */

#ifndef _Included_EgControl
#define _Included_EgControl
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
