/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EyeGazeJNI */

#ifndef _Included_EyeGazeJNI
#define _Included_EyeGazeJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EyeGazeJNI
 * Method:    EyeGazeInit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_EyeGazeJNI_EyeGazeInit
  (JNIEnv *, jobject, jint);

/*
 * Class:     EyeGazeJNI
 * Method:    EyeGazeShutDown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_EyeGazeJNI_EyeGazeShutDown
  (JNIEnv *, jobject);

/*
 * Class:     EyeGazeJNI
 * Method:    Calibrate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_EyeGazeJNI_Calibrate
  (JNIEnv *, jobject);

/*
 * Class:     EyeGazeJNI
 * Method:    getEyeGazeData
 * Signature: ()Ldata/EyeGazeData;
 */
JNIEXPORT jobject JNICALL Java_EyeGazeJNI_getEyeGazeData
  (JNIEnv *, jobject);

/*
 * Class:     EyeGazeJNI
 * Method:    EyeGazeLogStart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_EyeGazeJNI_EyeGazeLogStart
  (JNIEnv *, jobject);

/*
 * Class:     EyeGazeJNI
 * Method:    EyeGazeLogStop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_EyeGazeJNI_EyeGazeLogStop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
