/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestFunction */

#ifndef _Included_TestFunction
#define _Included_TestFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestFunction
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TestFunction_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
